# Generated by Django 4.2.10 on 2024-02-11 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='backstorys',
            field=models.TextField(default='', verbose_name='Предыстория'),
        ),
        migrations.AlterField(
            model_name='character',
            name='appearance',
            field=models.ImageField(default='', upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hitPoints',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Текущие Хиты'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hitPointsMax',
            field=models.IntegerField(default=999, verbose_name='Максимальные Хиты'),
        ),
    ]
