# Generated by Django 4.2.10 on 2024-02-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_character_backstorys_alter_character_appearance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='backstorys',
            field=models.CharField(default='', max_length=20, verbose_name='Предыстория'),
        ),
    ]
