# Generated by Django 4.2.10 on 2024-02-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_character_equipment_character_profiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='location',
            field=models.CharField(default='waterdeep', max_length=20, verbose_name='Текущее местополжение'),
        ),
    ]
