# Generated by Django 4.2.10 on 2024-03-03 03:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_character_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='attackundspells',
            field=models.TextField(default='', verbose_name='Атаки и Заклинания'),
        ),
        migrations.AddField(
            model_name='character',
            name='spellcastingAbilityScore',
            field=models.IntegerField(choices=[(0, 'Интелект'), (1, 'Мудрость'), (2, 'Харизма')], default='0', verbose_name='Базовые характеристики Заклинаний'),
        ),
        migrations.AlterField(
            model_name='character',
            name='appearance',
            field=models.ImageField(default='', upload_to='registration/photo/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hitDice',
            field=models.IntegerField(choices=[(0, ''), (1, '1d6'), (2, '1d8'), (3, '1d10'), (4, '1d12')], default='', verbose_name='Кости Хитов'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hitPoints',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Текущие Хиты'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hitPointsMax',
            field=models.IntegerField(default=1, verbose_name='Максимальные Хиты'),
        ),
    ]
