# Generated by Django 4.2.10 on 2024-03-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_character_hitdice_alter_character_hitpoints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='attackundspells',
            field=models.TextField(default='', verbose_name='Атаки и Заклинания'),
        ),
        migrations.AddField(
            model_name='character',
            name='spellcastingAbilityScore',
            field=models.IntegerField(choices=[(0, 'Интелект'), (1, 'Мудрость'), (2, 'Харизма')], default='0', verbose_name='Базовые характеристики Заклинаний'),
        ),
        migrations.AlterField(
            model_name='character',
            name='appearance',
            field=models.ImageField(default='', upload_to='registration/photo/', verbose_name='Изображение'),
        ),
    ]
