# Generated by Django 5.0.1 on 2024-05-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_alter_player_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='conspiraciesData',
            field=models.JSONField(default='   ', verbose_name='Информаци о заговорах'),
        ),
        migrations.AddField(
            model_name='character',
            name='lvlEight',
            field=models.JSONField(default=list, verbose_name='Уровень 8'),
        ),
        migrations.AddField(
            model_name='character',
            name='lvlFive',
            field=models.JSONField(default=list, verbose_name='Уровень 5'),
        ),
        migrations.AddField(
            model_name='character',
            name='lvlFour',
            field=models.JSONField(default=list, verbose_name='Уровень 4'),
        ),
        migrations.AddField(
            model_name='character',
            name='lvlNine',
            field=models.JSONField(default=list, verbose_name='Уровень 9'),
        ),
        migrations.AddField(
            model_name='character',
            name='lvlOne',
            field=models.JSONField(default=list, verbose_name='Уровень 1'),
        ),
        migrations.AddField(
            model_name='character',
            name='lvlSeven',
            field=models.JSONField(default=list, verbose_name='Уровень 7'),
        ),
        migrations.AddField(
            model_name='character',
            name='lvlSix',
            field=models.JSONField(default=list, verbose_name='Уровень 6'),
        ),
        migrations.AddField(
            model_name='character',
            name='lvlThree',
            field=models.JSONField(default=list, verbose_name='Уровень 3'),
        ),
        migrations.AddField(
            model_name='character',
            name='lvlTwo',
            field=models.JSONField(default=list, verbose_name='Уровень 2'),
        ),
    ]
