# Generated by Django 5.0.1 on 2024-06-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_remove_character_attackundspells_character_fail1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='spellcastingClass',
        ),
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.TextField(default='  ', verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='character',
            name='armourclass',
            field=models.IntegerField(default=0, verbose_name='Класс Доспеха'),
        ),
        migrations.AlterField(
            model_name='character',
            name='backstory',
            field=models.CharField(default='', max_length=20, verbose_name='Предыстория'),
        ),
        migrations.AlterField(
            model_name='character',
            name='backstorys',
            field=models.TextField(default='', verbose_name='Предыстория персонажа'),
        ),
        migrations.AlterField(
            model_name='character',
            name='conspiraciesData',
            field=models.JSONField(default=0, verbose_name='Информаци о заговорах'),
        ),
        migrations.AlterField(
            model_name='character',
            name='copper',
            field=models.IntegerField(default=0, verbose_name='Медные Монеты'),
        ),
        migrations.AlterField(
            model_name='character',
            name='electrum',
            field=models.IntegerField(default=0, verbose_name='Электровиумые Монеты'),
        ),
        migrations.AlterField(
            model_name='character',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='character',
            name='eyeColor',
            field=models.TextField(default='  ', verbose_name='Глаза'),
        ),
        migrations.AlterField(
            model_name='character',
            name='golden',
            field=models.IntegerField(default=0, verbose_name='Золотые Монеты'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hairColor',
            field=models.TextField(default='  ', verbose_name='Волосы'),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.TextField(default='  ', verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hitDice',
            field=models.IntegerField(choices=[(0, '1d6'), (1, '1d8'), (2, '1d10'), (3, '1d12')], default=0, verbose_name='Кости Хитов'),
        ),
        migrations.AlterField(
            model_name='character',
            name='levelEightTotal',
            field=models.IntegerField(default=0, verbose_name='Количество ячеек 8 уровня'),
        ),
        migrations.AlterField(
            model_name='character',
            name='levelFiveTotal',
            field=models.IntegerField(default=0, verbose_name='Количество ячеек 5 уровня'),
        ),
        migrations.AlterField(
            model_name='character',
            name='levelFourTotal',
            field=models.IntegerField(default=0, verbose_name='Количество ячеек 4 уровня'),
        ),
        migrations.AlterField(
            model_name='character',
            name='levelNineTotal',
            field=models.IntegerField(default=0, verbose_name='Количество ячеек 9 уровня'),
        ),
        migrations.AlterField(
            model_name='character',
            name='levelOneTotal',
            field=models.IntegerField(default=0, verbose_name='Количество ячеек 1 уровня'),
        ),
        migrations.AlterField(
            model_name='character',
            name='levelSevenTotal',
            field=models.IntegerField(default=0, verbose_name='Количество ячеек 7 уровня'),
        ),
        migrations.AlterField(
            model_name='character',
            name='levelSixTotal',
            field=models.IntegerField(default=0, verbose_name='Количество ячеек 6 уровня'),
        ),
        migrations.AlterField(
            model_name='character',
            name='levelThreeTotal',
            field=models.IntegerField(default=0, verbose_name='Количество ячеек 3 уровня'),
        ),
        migrations.AlterField(
            model_name='character',
            name='levelTwoTotal',
            field=models.IntegerField(default=0, verbose_name='Количество ячеек 2 уровня'),
        ),
        migrations.AlterField(
            model_name='character',
            name='platinum',
            field=models.IntegerField(default=0, verbose_name='Платиновые Монеты'),
        ),
        migrations.AlterField(
            model_name='character',
            name='silver',
            field=models.IntegerField(default=0, verbose_name='Серебряные Монеты'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skinColor',
            field=models.TextField(default='  ', verbose_name='Кожа'),
        ),
        migrations.AlterField(
            model_name='character',
            name='speed',
            field=models.IntegerField(default=0, verbose_name='Скорость'),
        ),
        migrations.AlterField(
            model_name='character',
            name='spellAttackBonus',
            field=models.IntegerField(default=0, verbose_name='Бонус Атаки Залинанием'),
        ),
        migrations.AlterField(
            model_name='character',
            name='spellSavingThrow',
            field=models.IntegerField(default=0, verbose_name='Сложность Спасброска'),
        ),
        migrations.AlterField(
            model_name='character',
            name='temporaryHitPoints',
            field=models.IntegerField(default=0, verbose_name='Временные Хиты'),
        ),
        migrations.AlterField(
            model_name='character',
            name='weight',
            field=models.TextField(default='  ', verbose_name='Вес'),
        ),
    ]
