# Generated by Django 5.0.1 on 2024-06-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_remove_character_spellcastingclass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Profiles/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
