# Generated by Django 5.0.1 on 2024-06-02 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_uploadedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='conspiraciesData',
        ),
        migrations.RemoveField(
            model_name='character',
            name='levelEightTotal',
        ),
        migrations.RemoveField(
            model_name='character',
            name='levelFiveTotal',
        ),
        migrations.RemoveField(
            model_name='character',
            name='levelFourTotal',
        ),
        migrations.RemoveField(
            model_name='character',
            name='levelNineTotal',
        ),
        migrations.RemoveField(
            model_name='character',
            name='levelOneTotal',
        ),
        migrations.RemoveField(
            model_name='character',
            name='levelSevenTotal',
        ),
        migrations.RemoveField(
            model_name='character',
            name='levelSixTotal',
        ),
        migrations.RemoveField(
            model_name='character',
            name='levelThreeTotal',
        ),
        migrations.RemoveField(
            model_name='character',
            name='levelTwoTotal',
        ),
        migrations.RemoveField(
            model_name='character',
            name='lvlEight',
        ),
        migrations.RemoveField(
            model_name='character',
            name='lvlFive',
        ),
        migrations.RemoveField(
            model_name='character',
            name='lvlFour',
        ),
        migrations.RemoveField(
            model_name='character',
            name='lvlNine',
        ),
        migrations.RemoveField(
            model_name='character',
            name='lvlOne',
        ),
        migrations.RemoveField(
            model_name='character',
            name='lvlSeven',
        ),
        migrations.RemoveField(
            model_name='character',
            name='lvlSix',
        ),
        migrations.RemoveField(
            model_name='character',
            name='lvlThree',
        ),
        migrations.RemoveField(
            model_name='character',
            name='lvlTwo',
        ),
        migrations.RemoveField(
            model_name='character',
            name='spellAttackBonus',
        ),
        migrations.RemoveField(
            model_name='character',
            name='spellSavingThrow',
        ),
        migrations.AddField(
            model_name='character',
            name='conspiracies0',
            field=models.TextField(default=list, verbose_name='Заговоры 1'),
        ),
        migrations.AddField(
            model_name='character',
            name='conspiracies1',
            field=models.TextField(default=list, verbose_name='Заговоры 2'),
        ),
        migrations.AddField(
            model_name='character',
            name='conspiracies10',
            field=models.TextField(default=list, verbose_name='Заговоры 11'),
        ),
        migrations.AddField(
            model_name='character',
            name='conspiracies11',
            field=models.TextField(default=list, verbose_name='Заговоры 12'),
        ),
        migrations.AddField(
            model_name='character',
            name='conspiracies12',
            field=models.TextField(default=list, verbose_name='Заговоры 13'),
        ),
        migrations.AddField(
            model_name='character',
            name='conspiracies2',
            field=models.TextField(default=list, verbose_name='Заговоры 3'),
        ),
        migrations.AddField(
            model_name='character',
            name='conspiracies3',
            field=models.TextField(default=list, verbose_name='Заговоры 4'),
        ),
        migrations.AddField(
            model_name='character',
            name='conspiracies4',
            field=models.TextField(default=list, verbose_name='Заговоры 5'),
        ),
        migrations.AddField(
            model_name='character',
            name='conspiracies5',
            field=models.TextField(default=list, verbose_name='Заговоры 6'),
        ),
        migrations.AddField(
            model_name='character',
            name='conspiracies6',
            field=models.TextField(default=list, verbose_name='Заговоры 7'),
        ),
        migrations.AddField(
            model_name='character',
            name='conspiracies7',
            field=models.TextField(default=list, verbose_name='Заговоры 8'),
        ),
        migrations.AddField(
            model_name='character',
            name='conspiracies8',
            field=models.TextField(default=list, verbose_name='Заговоры 9'),
        ),
        migrations.AddField(
            model_name='character',
            name='conspiracies9',
            field=models.TextField(default=list, verbose_name='Заговоры 10'),
        ),
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='registration.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='spellData',
            field=models.JSONField(default=list, verbose_name='Информация о заклинаниях'),
        ),
        migrations.AddField(
            model_name='character',
            name='spellSlots',
            field=models.JSONField(default=list, verbose_name='Информация о слотах'),
        ),
        migrations.AddField(
            model_name='character',
            name='spellSlotsBoolean',
            field=models.JSONField(default=list, verbose_name='Информация о слотах чекбоксы'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hitDice',
            field=models.CharField(default=0, max_length=20, verbose_name='Кости Хитов'),
        ),
        migrations.AlterField(
            model_name='character',
            name='spellcastingAbilityScore',
            field=models.TextField(choices=[(0, 'Интелект'), (1, 'Мудрость'), (2, 'Харизма')], default='0', verbose_name='Базовые характеристики Заклинаний'),
        ),
    ]
