# Generated by Django 5.0.1 on 2024-06-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_alter_character_additionalfeatures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='appearance',
            field=models.FileField(blank=True, default='', upload_to='registration/photo/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='character',
            name='spellcastingAbilityScore',
            field=models.TextField(default='0', verbose_name='Базовые характеристики Заклинаний'),
        ),
        migrations.AlterField(
            model_name='character',
            name='temporaryHitPoints',
            field=models.TextField(blank=True, default=0, null=True, verbose_name='Временные Хиты'),
        ),
    ]
