# Generated by Django 5.0.1 on 2024-06-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_alter_character_appearance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='сharacterPlayer',
        ),
    ]
