# Generated by Django 5.0.1 on 2024-06-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_remove_character_сharacterplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hasMagicFlyingItem',
            field=models.BooleanField(blank=True, default=False, verbose_name='Магический пердмет для полетов'),
        ),
        migrations.AddField(
            model_name='character',
            name='hasMagicWalkingItem',
            field=models.BooleanField(blank=True, default=False, verbose_name='Магический наземный премдмет'),
        ),
        migrations.AlterField(
            model_name='character',
            name='backstory',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Предыстория'),
        ),
        migrations.AlterField(
            model_name='character',
            name='characterClass',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hitDice',
            field=models.CharField(default=0, max_length=50, verbose_name='Кости Хитов'),
        ),
        migrations.AlterField(
            model_name='character',
            name='location',
            field=models.CharField(default='waterdeep', max_length=50, verbose_name='Текущее местополжение'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Имя персонажа'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Раса'),
        ),
        migrations.AlterField(
            model_name='character',
            name='worldviews',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Мировозрение'),
        ),
    ]
