# Generated by Django 5.0.1 on 2024-06-08 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_character_hasmagicflyingitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email_verification_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='player',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
