# Generated by Django 5.0.1 on 2024-06-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_player_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='WayCoordinates',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Координаты пути'),
        ),
        migrations.AddField(
            model_name='character',
            name='dateOfEnd',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время конца пути'),
        ),
        migrations.AddField(
            model_name='character',
            name='dateOfStart',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала пути'),
        ),
        migrations.AddField(
            model_name='character',
            name='inWay',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Находится ли персонаж в пути'),
        ),
        migrations.AddField(
            model_name='character',
            name='newCityLocation',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Город к которому идет персонаж'),
        ),
    ]
