# Generated by Django 5.0.1 on 2024-06-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_character_waycoordinates_character_dateofend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='WayCoordinates',
        ),
    ]
