# Generated by Django 5.0.1 on 2024-06-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_remove_character_waycoordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='WayCoordinates',
            field=models.JSONField(blank=True, null=True, verbose_name='Координаты пути'),
        ),
    ]
