# Generated by Django 5.0.1 on 2024-06-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_character_waycoordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='copper',
            field=models.IntegerField(blank=True, default=0, verbose_name='Медные Монеты'),
        ),
        migrations.AlterField(
            model_name='character',
            name='electrum',
            field=models.IntegerField(blank=True, default=0, verbose_name='Электровиумые Монеты'),
        ),
        migrations.AlterField(
            model_name='character',
            name='golden',
            field=models.IntegerField(blank=True, default=0, verbose_name='Золотые Монеты'),
        ),
        migrations.AlterField(
            model_name='character',
            name='location',
            field=models.TextField(blank=True, default='waterdeep', max_length=50, verbose_name='Текущее местополжение'),
        ),
        migrations.AlterField(
            model_name='character',
            name='platinum',
            field=models.IntegerField(blank=True, default=0, verbose_name='Платиновые Монеты'),
        ),
        migrations.AlterField(
            model_name='character',
            name='silver',
            field=models.IntegerField(blank=True, default=0, verbose_name='Серебряные Монеты'),
        ),
    ]
