# Generated by Django 5.0.1 on 2024-06-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_character_selectedtransport'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ifFlying',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Летающий'),
        ),
    ]
