# Generated by Django 4.2.10 on 2024-03-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(default='', max_length=20, verbose_name='Имя персонажа')),
                ('ClassCheckBox', models.BooleanField(default='', max_length=20, verbose_name='Э чи нема')),
            ],
        ),
    ]
