# Generated by Django 4.2.10 on 2024-03-03 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DefaultChoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=100)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DefaultChoice.classes')),
            ],
        ),
    ]
