# Generated by Django 4.2.10 on 2024-03-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefaultChoice', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(default='', max_length=20, verbose_name='Имя Класса')),
                ('ClassCheckBox', models.BooleanField(default='1', max_length=20, verbose_name='Имеется ли')),
            ],
        ),
        migrations.AlterField(
            model_name='classes',
            name='ClassCheckBox',
            field=models.BooleanField(default='1', max_length=20, verbose_name='Имеется ли'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='ClassName',
            field=models.CharField(default='', max_length=20, verbose_name='Имя Класса'),
        ),
    ]
