# Generated by Django 4.2.10 on 2024-03-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefaultChoice', '0004_spells'),
    ]

    operations = [
        migrations.AddField(
            model_name='spells',
            name='SpellEngName',
            field=models.CharField(default='', max_length=20, verbose_name='Имя Заклинания на Английском'),
        ),
    ]
