# Generated by Django 4.2.10 on 2024-03-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefaultChoice', '0005_spells_spellengname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spells',
            name='SpellCastTimeText',
            field=models.TextField(default='Действие', max_length=20, verbose_name='Еденица измерения'),
        ),
    ]
