# Generated by Django 4.2.10 on 2024-03-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefaultChoice', '0006_alter_spells_spellcasttimetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='spells',
            name='SpellConcentration',
            field=models.BooleanField(default='0', verbose_name='Концентрация'),
        ),
        migrations.AlterField(
            model_name='spells',
            name='SpellArchtipes',
            field=models.TextField(default='0', verbose_name='Архетипы'),
        ),
        migrations.AlterField(
            model_name='spells',
            name='SpellCastTimeText',
            field=models.TextField(default='Действие', verbose_name='Еденица измерения'),
        ),
        migrations.AlterField(
            model_name='spells',
            name='SpellMaterials',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Материалы'),
        ),
        migrations.AlterField(
            model_name='spells',
            name='SpellSource',
            field=models.TextField(default='Players handbook', verbose_name='Источник'),
        ),
    ]
