# Generated by Django 4.2.10 on 2024-03-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefaultChoice', '0007_spells_spellconcentration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spells',
            name='SpellDistance',
            field=models.CharField(default='', max_length=40, verbose_name='Дистания'),
        ),
    ]
