# Generated by Django 4.2.10 on 2024-03-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefaultChoice', '0008_alter_spells_spelldistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spells',
            name='SpellArchtipes',
            field=models.TextField(blank=True, default='', verbose_name='Архетипы'),
        ),
        migrations.AlterField(
            model_name='spells',
            name='SpellCaster',
            field=models.TextField(default='', verbose_name='Класс с маленькой буквы!'),
        ),
        migrations.AlterField(
            model_name='spells',
            name='SpellDuration',
            field=models.TextField(default='Мгновенно', max_length=20, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='spells',
            name='SpellLevelDescription',
            field=models.TextField(blank=True, default='', verbose_name='На больших уровнях'),
        ),
        migrations.AlterField(
            model_name='spells',
            name='SpellMaterials',
            field=models.TextField(blank=True, default='', verbose_name='Материалы'),
        ),
    ]
