# Generated by Django 4.2.10 on 2024-03-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefaultChoice', '0010_wheelspells_alter_spells_spellengname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spells',
            name='SpellDistanceText',
            field=models.CharField(blank=True, default='Футы', max_length=20, verbose_name='Еденица измерения'),
        ),
        migrations.AlterField(
            model_name='spells',
            name='SpellDuration',
            field=models.TextField(default='Мгновенно', verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='wheelspells',
            name='SpellCheckBox',
            field=models.BooleanField(default='0', verbose_name='Имеется ли'),
        ),
    ]
