# Generated by Django 4.2.9 on 2024-02-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название города')),
                ('coordinates', models.CharField(max_length=20, verbose_name='Координаты')),
                ('icon', models.CharField(default='map/img/CityIcon/', max_length=50, verbose_name='Ссылка на картинку города')),
                ('description', models.TextField(verbose_name='Описание города')),
            ],
        ),
    ]
