# Generated by Django 4.2.9 on 2024-02-09 07:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название дороги')),
                ('coordinates', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=15)),
            ],
            options={
                'verbose_name': 'Дорога',
                'verbose_name_plural': 'Дороги',
            },
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterField(
            model_name='cities',
            name='icon',
            field=models.ImageField(default='CityIcon/point.png', upload_to='CityIcon/'),
        ),
    ]
