# Generated by Django 4.2.9 on 2024-02-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_roads_alter_cities_options_alter_cities_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roads',
            name='coordinates',
            field=models.TextField(verbose_name='coordinates'),
        ),
    ]
