# Generated by Django 5.0.1 on 2024-02-23 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_roads_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.CharField(max_length=30, verbose_name='Главный заголвовк')),
                ('Body', models.TextField(verbose_name='Главный текст')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('Header2', models.CharField(default='0', max_length=30, verbose_name='Второстепенный заголовок')),
                ('Body2', models.TextField(default='0', verbose_name='Второстепенный текст')),
                ('GeneralImage', models.ImageField(upload_to='GeneralNewsImage/')),
                ('SecondaryImage', models.ImageField(default='0', upload_to='GeneralNewsImage/')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
