# Generated by Django 5.0.1 on 2024-03-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_news_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='date',
            new_name='dateOfPublishing',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='Header',
            new_name='mainHeader',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='GeneralImage',
            new_name='mainImage',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='Body',
            new_name='mainText',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='Header2',
            new_name='secondaryHeader',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='SecondaryImage',
            new_name='secondaryImage',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='Body2',
            new_name='secondaryText',
        ),
    ]
