# Generated by Django 5.0.1 on 2024-06-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_rename_author_news_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='cityPhoto',
            field=models.ImageField(default='CityPhotos/default.png', upload_to='CityPhotos/'),
        ),
    ]
