# Generated by Django 5.0.1 on 2024-06-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_cities_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='cityPhoto',
            field=models.ImageField(default='CityPhotos/default.jpg', upload_to='CityPhotos/'),
        ),
    ]
