# Generated by Django 4.2.10 on 2024-06-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_alter_cities_cityphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeaRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название Морской дороги')),
                ('coordinates', models.TextField(verbose_name='coordinates')),
            ],
            options={
                'verbose_name': 'Морская дорога',
                'verbose_name_plural': 'Морские дороги',
            },
        ),
    ]
