# Generated by Django 4.2.10 on 2024-06-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_searoute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='cityPhoto',
            field=models.ImageField(default='CityPhotos/default.png', upload_to='CityPhotos/'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='coordinates',
            field=models.CharField(max_length=50, verbose_name='Координаты'),
        ),
    ]
